template update
mineiros-io/terraform-google-service-account-iam pull request #17
Opened 2022-09-12 10:07 UTC by waxb

- chore: update changelog
- chore: update module from template and tests
- feat: computed members added

2022-09-27 09:14 UTC, mariux requested changes

2022-09-27 09:14 UTC, mariux commented on test/terramate_provider_versions.tm.hcl
> +  minimum_provider_version    = "4.0"
please also drop support for <4.x in versions.tf

2022-09-27 09:15 UTC, mariux requested changes

2022-09-27 09:37 UTC, waxb commented on variables.tf
> +variable "computed_members_map" {
i copied this a long time ago, my bad!

2022-09-27 09:47 UTC, mariux requested changes

2022-09-27 09:47 UTC, mariux commented on variables.tf
> +    condition     = alltrue([for m in var.members : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain|computed):)", m))])
:boom: this disables OIDC ;)

2022-10-07 12:05 UTC, zied-elouaer submitted a review, later dismissed
LGTM

2022-10-08 17:03 UTC, mariux requested changes

2022-10-08 17:03 UTC, mariux commented on variables.tf
> +    condition     = alltrue([for k, v in var.computed_members_map : can(regex("^(allUsers|allAuthenticatedUsers|(user|serviceAccount|group|domain):)", v))])
principalSet is missing.

2022-10-10 11:56 UTC, mariux approved these changes

2022-10-10 15:38 UTC, merged